package com.shu.backend.domain.adminaudit.enums;

public enum AdminAuditAction {
    VIEW_POST_DETAIL,
    HIDE_POST,
    RESTORE_POST,
    HIDE_COMMENT,
    RESTORE_COMMENT,
    APPROVE_REPORT,
    REJECT_REPORT,
    WARN_REPORT,
    CANCEL_PENALTY,
    VIEW_VERIFICATION_REQUEST,
    APPROVE_VERIFICATION_REQUEST,
    REJECT_VERIFICATION_REQUEST,
    VIEW_INQUIRY_DETAIL,
    ANSWER_INQUIRY
}
