server:
  port: 8080

spring:
  profiles:
    active: local

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    baseline-description: "baseline"

  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/shu?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 7165
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: wangkihong8130@gmail.com
    password: zwkxeqkkbwvogjmi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

  jackson:
    serialization:
      fail-on-empty-beans: false

  data:
    redis:
      host: localhost
      port: 6379

mail:
  from: wangkihong8130@gmail.com


debug: true
logging:
  level:
    root: INFO
    org.springframework.boot.autoconfigure: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE   # 바인딩 값 출력
    org.springframework.web: INFO
    com.shu.backend: DEBUG      # 프로젝트 패키지 기준
    p6spy: INFO

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
  access-token-expiration: 3600000        # 1시간 (ms)
  refresh-token-expiration: 1209600000    # 14일 (ms)

cors:
  allowed-origins: "http://localhost:3000, https://your-app-domain.com"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true

websocket:
  endpoint: "/ws/chat"
  allowed-origins: "*"  # 개발 단계 / 운영 시 실제 도메인만 허용

# 로컬 파일 저장용 설정 (배포 후 비활성화)
file:
  upload-dir:
    student-card: uploads/student-card   # 실제 로컬 폴더 (프로젝트 기준)
    chat: uploads/chat
  storage:
    bucket: local-bucket                 # 로컬에선 의미 거의 없음
    student-card-dir: student-card
    base-url: http://localhost:8080/uploads



firebase:
  service-account-path: keys/firebase-service-account.json

viewcount:
  mode: PESSIMISTIC


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99


#  # S3 기반 파일 스토리지 설정 （배포후 이를 활성화）
#file:
#  storage:
#    bucket: teenple-student-card
#    student-card-dir: student-card
#    chat-dir: chat
#    base-url: https://cdn.teenple.com

#배포후 접근키 비밀키 삽입
cloud:
  aws:
#    credentials:
#      access-key
#      secret-key:
    region:
      static: ap-northeast-2

#file:#  chat-dir: chat
##  student-card-dir: student-card
##  base-url: https://...
##  bucket: ...


